config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :tickets
  # root to: 'visitors#index'
  devise_for :users
  
  root :to => "users#welcome"

  resources :users do
    collection do
      get 'dashboard'
    end
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :ticket_replies, :dependent => :destroy
  has_many :ticket_comments, :dependent => :destroy
  has_many :children, :class_name => "Ticket", :foreign_key => :parent_id
  belongs_to :company
  belongs_to :raised_by, :class_name => "User"
  belongs_to :assigned_to, :class_name => "User"
end

app/models/ticket_comment.rb
class TicketComment < ActiveRecord::Base
  belongs_to :ticket
end

app/models/ticket_reply.rb
class TicketReply < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :replied_by, , :class_name => "User"
  belongs_to :replied_to, , :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tickets
  has_many :ticket_replies
  has_many :ticket_comments, foreign_key: :commented_by
  belongs_to :company
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :parent_id)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:issue_type, :issue_subject, :issue_description, :raised_by, :raised_at, :datetime, :status, :assigned_to)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!
	
	def dashboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
  end

  def edit
  end

  def update
  end

  def welcome
    if user_signed_in?
      redirect_to dashboard_users_path
    else
      redirect_to new_session_path(User.new)
    end
  end

  def dashboard
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def hidden_if_empty?(text)
    "hide-me" if text.blank?
  end

  def apply_if_true(x, class_name, other_name = nil)
    x ? class_name : other_name
  end

  def if_current(path, class_name)
    current_page?(path) ? class_name : nil
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.haml
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :parent_id
    = f.number_field :parent_id
  .actions
    = f.submit 'Save'

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %thead
    %tr
      %th Name
      %th Parent
      %th
      %th
      %th

  %tbody
    - @companies.each do |company|
      %tr
        %td= company.name
        %td= company.parent_id
        %td= link_to 'Show', company
        %td= link_to 'Edit', edit_company_path(company)
        %td= link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @company.name
%p
  %b Parent:
  = @company.parent_id

= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top.hori_padding
  .navbar-header
    - if user_signed_in?
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-brand.f21= link_to "Vyavasay", dashboard_users_path, class: "logo-color"
  .collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %ul.nav.navbar-nav.right
    %li.inline-block
      = link_to 'Raise New Ticket', new_ticket_path
    %li.dropdown
      %a.inline-block.dropdown-toggle.navbar-brand{"data-toggle" => "dropdown"}
        Settings
        %b.caret
      %ul.dropdown-menu  
        %li
          %a= link_to 'Account', edit_user_path(current_user)
        %li
          %a= link_to 'Users', users_path(current_user)
        %li
          %a= link_to 'Sign Out', destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Vyavasay'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Vyavasay'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    %header
      #loading
        Loading...
      = render 'layouts/navigation'
    %main{:role => "main"}
      #flash-container
        .flash.auto-hide.notice.alert-success{:class => hidden_if_empty?(notice)}
          .inner_notice.cal= notice
          .fr= link_to "x", "#", :class => "hide-flash"
          .clear
        .flash.auto-hide.alert.alert-danger{:class => hidden_if_empty?(alert)}
          .inner_alert= alert
          .fr= link_to "x", "#", :class => "hide-flash"
          .clear
      = yield
    = yield :page_js

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/tickets/_form.html.haml
= form_for @ticket do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :issue_type
    = f.text_field :issue_type
  .field
    = f.label :issue_subject
    = f.text_field :issue_subject
  .field
    = f.label :issue_description
    = f.text_field :issue_description
  .field
    = f.label :raised_by
    = f.number_field :raised_by
  .field
    = f.label :raised_at
    = f.text_field :raised_at
  .field
    = f.label :datetime
    = f.text_field :datetime
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :assigned_to
    = f.number_field :assigned_to
  .actions
    = f.submit 'Save'

app/views/tickets/edit.html.haml
%h1 Editing ticket

= render 'form'

= link_to 'Show', @ticket
\|
= link_to 'Back', tickets_path

app/views/tickets/index.html.haml
%h1 Listing tickets

%table
  %thead
    %tr
      %th Issue type
      %th Issue subject
      %th Issue description
      %th Raised by
      %th Raised at
      %th Datetime
      %th Status
      %th Assigned to
      %th
      %th
      %th

  %tbody
    - @tickets.each do |ticket|
      %tr
        %td= ticket.issue_type
        %td= ticket.issue_subject
        %td= ticket.issue_description
        %td= ticket.raised_by
        %td= ticket.raised_at
        %td= ticket.datetime
        %td= ticket.status
        %td= ticket.assigned_to
        %td= link_to 'Show', ticket
        %td= link_to 'Edit', edit_ticket_path(ticket)
        %td= link_to 'Destroy', ticket, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ticket', new_ticket_path

app/views/tickets/new.html.haml
%h1 New ticket

= render 'form'

= link_to 'Back', tickets_path

app/views/tickets/show.html.haml
%p#notice= notice

%p
  %b Issue type:
  = @ticket.issue_type
%p
  %b Issue subject:
  = @ticket.issue_subject
%p
  %b Issue description:
  = @ticket.issue_description
%p
  %b Raised by:
  = @ticket.raised_by
%p
  %b Raised at:
  = @ticket.raised_at
%p
  %b Datetime:
  = @ticket.datetime
%p
  %b Status:
  = @ticket.status
%p
  %b Assigned to:
  = @ticket.assigned_to

= link_to 'Edit', edit_ticket_path(@ticket)
\|
= link_to 'Back', tickets_path

app/views/visitors/index.html.erb
<h3>Welcome</h3>